### ISSUE TITLE
Better README / Documentation

### ISSUE THREAD

**Issue by Jaezmien** [Jaezmien/FiMSharp#3]
**TODO**

- [x] Compiling the DLLs and Test program using the batch file
- [x] Running `FiMSharp.Test`
- [x] Actually useful documentation comments for important functions

**Comment by Jaezmien** [comment]
1. and 2. should be covered by dd70d7e76c419a098e33bac87284e6735482022a

**Comment by Jaezmien** [comment]
3. is currently covered by [function-docs](/Jaezmien/FiMSharp/tree/function-docs) branch, but will be merged to master in the future as docs comments should be made by default.

**Comment by Jaezmien** [comment]
function-docs branch merged to master.
